AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create SNS topic and Lambda function, and trigger Lambda from SNS

Resources:
  MySNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "MySNSTopic"
  
  MyLambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: "MyLambdaExecutionRole"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaBasicExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: "SNSPublishPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "sns:Publish"
                Resource: "*"

  MyLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: "MyLambdaFunction"
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Code:
        S3Bucket: "your-s3-bucket"  # Lambdaコードを格納するS3バケット
        S3Key: "path/to/your-lambda-code.zip"
      Runtime: "go1.x"
      Timeout: 30
      MemorySize: 128

  MyLambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref MyLambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "sns.amazonaws.com"
      SourceArn: !Ref MySNSTopic

  MySNSSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Protocol: "lambda"
      TopicArn: !Ref MySNSTopic
      Endpoint: !GetAtt MyLambdaFunction.Arn

Outputs:
  SNSTopicARN:
    Description: "SNS Topic ARN"
    Value: !Ref MySNSTopic

  LambdaFunctionName:
    Description: "Lambda function name"
    Value: !Ref MyLambdaFunction
